# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170131_0553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('can_create_edit_delete_authors', 'create edit delete authors'),)},
        ),
    ]
