# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170131_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_create_edit_delete_books', 'create edit delete books'),)},
        ),
    ]
